# Generated by Django 5.1.4 on 2026-06-18 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.CharField(choices=[('FACULTY', 'Faculty Advisor'), ('HOD', 'Head of Department'), ('WARDEN', 'Warden'), ('ADMIN', 'Administrator')], max_length=20)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('FORWARDED', 'Forwarded')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'db_table': 'approvals',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requires_faculty_approval', models.BooleanField(default=True)),
                ('requires_hod_approval', models.BooleanField(default=True)),
                ('requires_warden_approval', models.BooleanField(default=True)),
                ('enable_emergency_fast_track', models.BooleanField(default=False)),
                ('max_emergency_hours', models.PositiveIntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval Configuration',
                'verbose_name_plural': 'Approval Configurations',
                'db_table': 'approval_configurations',
            },
        ),
    ]
