# Generated by Django 5.1.4 on 2026-06-18 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('departments', '0001_initial'),
        ('outpass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='outpass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='outpass.outpassrequest'),
        ),
        migrations.AddField(
            model_name='approvalconfiguration',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_config', to='departments.department'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['outpass', 'approval_level'], name='approvals_outpass_9253b9_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'action'], name='approvals_approve_bd0ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['created_at'], name='approvals_created_223946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('outpass', 'approval_level')},
        ),
    ]
