# Generated by Django 5.1.4 on 2026-06-18 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpassRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outpass_type', models.CharField(choices=[('GENERAL', 'General'), ('MEDICAL', 'Medical'), ('EMERGENCY', 'Emergency'), ('HOME', 'Home Visit'), ('OTHER', 'Other')], default='GENERAL', max_length=50)),
                ('reason', models.TextField()),
                ('destination', models.CharField(max_length=500)),
                ('departure_datetime', models.DateTimeField()),
                ('expected_return_datetime', models.DateTimeField()),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FACULTY_APPROVED', 'Faculty Approved'), ('HOD_APPROVED', 'HOD Approved'), ('WARDEN_APPROVED', 'Warden Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('requires_faculty_approval', models.BooleanField(default=True)),
                ('requires_hod_approval', models.BooleanField(default=True)),
                ('requires_warden_approval', models.BooleanField(default=True)),
                ('current_approval_level', models.CharField(default='FACULTY', max_length=20)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoke_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_outpasses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpass_requests', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Outpass Request',
                'verbose_name_plural': 'Outpass Requests',
                'db_table': 'outpass_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='outpass_req_student_6fa343_idx'), models.Index(fields=['status', 'created_at'], name='outpass_req_status_787e6b_idx'), models.Index(fields=['departure_datetime', 'expected_return_datetime'], name='outpass_req_departu_fb109e_idx'), models.Index(fields=['status', 'current_approval_level'], name='outpass_req_status_082544_idx'), models.Index(fields=['student', 'departure_datetime'], name='outpass_req_student_b88e67_idx')],
            },
        ),
    ]
