# Generated by Django 5.1.4 on 2026-06-18 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ManyToManyField(blank=True, limit_choices_to={'role': 'FACULTY'}, related_name='faculty_departments', to=settings.AUTH_USER_MODEL)),
                ('hod', models.OneToOneField(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('BOYS', 'Boys Hostel'), ('GIRLS', 'Girls Hostel'), ('CO_ED', 'Co-Educational')], default='CO_ED', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warden', models.OneToOneField(blank=True, limit_choices_to={'role': 'WARDEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_hostel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostels',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'is_active'], name='departments_code_f53fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code', 'is_active'], name='courses_code_b40021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
    ]
