# Generated by Django 5.1.4 on 2026-06-18 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpass', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('EXIT', 'Exit'), ('ENTRY', 'Entry')], db_index=True, max_length=10)),
                ('verification_result', models.CharField(choices=[('VALID', 'Valid'), ('INVALID_TOKEN', 'Invalid Token'), ('NOT_APPROVED', 'Not Approved'), ('EXPIRED', 'Expired'), ('ALREADY_USED', 'Already Used'), ('REVOKED', 'Revoked'), ('STUDENT_INACTIVE', 'Student Inactive'), ('CANCELLED', 'Cancelled')], default='VALID', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_logs', to='outpass.outpassrequest')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry/Exit Log',
                'verbose_name_plural': 'Entry/Exit Logs',
                'db_table': 'entry_exit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outpass', 'movement_type'], name='entry_exit__outpass_e5658c_idx'), models.Index(fields=['verified_by', 'created_at'], name='entry_exit__verifie_50b1ea_idx'), models.Index(fields=['exit_time', 'entry_time'], name='entry_exit__exit_ti_212811_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_time', models.DateTimeField()),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('OUTSIDE', 'Outside Campus'), ('RETURNED', 'Returned to Campus'), ('OVERSTAY', 'Overstayed')], default='OUTSIDE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_history', to='outpass.outpassrequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_history', to='students.studentprofile')),
                ('verified_by_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movement History',
                'verbose_name_plural': 'Movement Histories',
                'db_table': 'movement_history',
                'ordering': ['-exit_time'],
                'indexes': [models.Index(fields=['student', 'status'], name='movement_hi_student_91653a_idx'), models.Index(fields=['exit_time', 'entry_time'], name='movement_hi_exit_ti_ec6e38_idx')],
            },
        ),
    ]
