# Generated by Django 5.1.4 on 2026-06-18 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Student ID')),
                ('enrollment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('current_year', models.PositiveSmallIntegerField(default=1)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('permanent_address', models.TextField(blank=True)),
                ('current_address', models.TextField(blank=True)),
                ('is_in_hostel', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='departments.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='departments.department')),
                ('faculty_advisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='departments.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
                'indexes': [models.Index(fields=['student_id', 'is_active'], name='student_pro_student_6f4293_idx'), models.Index(fields=['enrollment_number'], name='student_pro_enrollm_5a5ede_idx'), models.Index(fields=['department', 'course'], name='student_pro_departm_614631_idx'), models.Index(fields=['batch', 'current_year'], name='student_pro_batch_332500_idx'), models.Index(fields=['faculty_advisor'], name='student_pro_faculty_9c786a_idx'), models.Index(fields=['hostel', 'is_in_hostel'], name='student_pro_hostel__7e41f3_idx')],
            },
        ),
    ]
