# Generated by Django 5.1.4 on 2026-06-18 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outpass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_pass', to='outpass.outpassrequest')),
            ],
            options={
                'verbose_name': 'QR Pass',
                'verbose_name_plural': 'QR Passes',
                'db_table': 'qr_passes',
                'indexes': [models.Index(fields=['token', 'expires_at'], name='qr_passes_token_e9ece6_idx'), models.Index(fields=['outpass', 'is_revoked'], name='qr_passes_outpass_b8f623_idx')],
            },
        ),
    ]
